services:
  api:
    image: "ocorrencia-api:latest"
    container_name: ocorrencia-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
      - minio
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/ocorrenciaapi"
      - "SPRING_DATASOURCE_USERNAME=admocorrencia"
      - "SPRING_DATASOURCE_PASSWORD=bebaagua!"
